version: '3.3'

services:
  service:
    image: "mtk246/${REPO_NAME}:${REF_NAME}"
    container_name: "${REPO_NAME}-${REF_NAME}"
    networks:
      - server
    ports:
      - 8002:8000
    restart: always

networks:
  server:
    driver: bridge
