name: Deploy Node.js App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # Step 2: Create an .env file (optional, based on your variables)
      - name: Create .env file
        run: |
          echo "SERVER_PORT=9000" >> .env
          echo "DATABASE_URL='postgresql://mtk246:mtkMTK123@100.109.254.2:5432/university_megazine?schema=public'" >> .env
          echo "ROCKETCHAT_URL='https://chat.mtktechlab.com'" >> .env
          echo "LOCAL_HOST='http://localhost'" >> .env
          echo "MINIO_ENDPOINT='file-api.mtktechlab.com'" >> .env
          echo "MINIO_PORT=9000" >> .env
          echo "MINIO_USE_SSL=true" >> .env
          echo "MINIO_ACCESS_KEY=access_key_1" >> .env
          echo "MINIO_SECRET_KEY=2mU5esnr1IUycUkaWOFTY7UyDV2RVZtndAsDLFbV" >> .env
          echo "MINIO_BUCKET_NAME=megazine" >> .env
          echo "MAILJET_APIKEY=12ae5adcc9a5830c1e76c47505fbdd35" >> .env
          echo "MAILJET_SECRET_KEY=889f2b70d5f4398a924a53ed96e738a2" >> .env

      # Step 3: SSH to server and deploy
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_TAILSCALE_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/dev/bee-express-admin-backend
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            echo "REPO_NAME=${{ github.event.repository.name }}" > .env
            echo "REF_NAME=${{ github.ref_name }}" >> .env
            echo "SERVER_PORT=9000" >> .env
            echo "DATABASE_URL='postgresql://mtk246:mtkMTK123@100.109.254.2:5432/university_megazine?schema=public'" >> .env
            echo "ROCKETCHAT_URL='https://chat.mtktechlab.com'" >> .env
            echo "LOCAL_HOST='http://localhost'" >> .env
            echo "MINIO_ENDPOINT='file-api.mtktechlab.com'" >> .env
            echo "MINIO_PORT=9000" >> .env
            echo "MINIO_USE_SSL=true" >> .env
            echo "MINIO_ACCESS_KEY=access_key_1" >> .env
            echo "MINIO_SECRET_KEY=2mU5esnr1IUycUkaWOFTY7UyDV2RVZtndAsDLFbV" >> .env
            echo "MINIO_BUCKET_NAME=megazine" >> .env
            echo "MAILJET_APIKEY=12ae5adcc9a5830c1e76c47505fbdd35" >> .env
            echo "MAILJET_SECRET_KEY=889f2b70d5f4398a924a53ed96e738a2" >> .env
            docker buildx build --platform linux/amd64 -t mtk246/${{ github.event.repository.name }}:${{ github.ref_name }} --load .
            docker-compose --env-file .env down || true
            docker-compose --env-file .env up -d
